name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 0.2.3
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  envied:
    git:
      url: https://github.com/skyronnel/envied.git
      ref: main
      path: packages/envied
  build: ^2.3.0
  dotenv: ^3.0.0
  source_gen: ^0.9.10+5
  analyzer: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  source_gen_test: ^1.0.3
